-- MySQL Script generated by MySQL Workbench
-- Út 22. ledna 2019, 14:05:18 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hackTest2019
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hackTest2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackTest2019` DEFAULT CHARACTER SET utf8 ;
USE `hackTest2019` ;

-- -----------------------------------------------------
-- Table `hackTest2019`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackTest2019`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackTest2019`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackTest2019`.`score` (
  `user_idUser` INT NOT NULL,
  `level0` TINYINT NULL,
  `level1` TINYINT NULL,
  `level2` TINYINT NULL,
  `level3` TINYINT NULL,
  `level4` TINYINT NULL,
  `level5` TINYINT NULL,
  `level6` TINYINT NULL,
  `level7` TINYINT NULL,
  `level8` TINYINT NULL,
  INDEX `fk_score_user_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_score_user`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `hackTest2019`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackTest2019`.`newEmail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackTest2019`.`newEmail` (
  `user_idUser` INT NOT NULL,
  `newEmail` VARCHAR(45) NULL,
  INDEX `fk_newEmail_user1_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_newEmail_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `hackTest2019`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
